[package]
name = "utca-pv-sanity-check"
version = "0.1.0"
edition = "2021"

[dependencies]
epics-ca = { path = "./epics-ca" }
futures = "0.3.25"
async-std = { version = "1.12.0", features = ["attributes"] }
